language: ruby
cache: bundler
bundler_args: "--binstubs --without documentation --path ../bundle --retry=3 --jobs=3"
before_script: bundle exec jbundle install
script: bundle exec rspec spec --require spec_helper

jdk:
  - oraclejdk8

addons:
  code_climate:
    repo_token: 41e13c614d15b0a661fd818b8f1a0817356182caae61fa997807dba121d244af